# Use postgres/example user/password credentials
version: '3.1'
services:
  rabbitmq-manage:
    image: rabbitmq:3-management
    ports:
        - '5672:5672'
        - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=srt
      - RABBITMQ_DEFAULT_PASS=srt
